# Generated by Django 5.1.7 on 2025-05-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productimage",
            name="unique_primary_image_per_product",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(default="10.jpg", upload_to="product_images/"),
        ),
    ]
