# Generated by Django 5.1.7 on 2025-06-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.URLField(),
        ),
    ]
