# Generated by Django 5.1.7 on 2025-05-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_tag_product_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"], "verbose_name_plural": "Tags"},
        ),
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="value",
            field=models.CharField(default="default", max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("name", "value")},
        ),
    ]
