# Generated by Django 5.1.7 on 2025-05-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_tag_options_tag_description_tag_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="tag",
            name="value",
            field=models.CharField(default="default", max_length=50),
        ),
    ]
