# Generated by Django 5.1.7 on 2025-05-27 23:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_tag_name_alter_tag_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal(
                            "0.01000000000000000020816681711721685132943093776702880859375"
                        )
                    )
                ],
            ),
        ),
    ]
